imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
#    - { resource: "@LL/CoreBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true


stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable:   true
            translatable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


ll_core:
    menus:
        products:
            beautyName: Produits
        provider:
            beautyName: Fournisseurs
        production:
            beautyName: Fiche de fabrication
    entities:
        product:
            beautyName: Produits
            menu: products
            class: LL\CoreBundle\Entity\Product
            form: LL\CoreBundle\Form\ProductType
            views: product
            listProperties:
                name:
                    dataName: name
                    beautyName: Nom
                    type: string
                isAllergen:
                    dataName: isAllergen
                    beautyName: Produit allergène
                    type: boolean
                priceHt:
                    dataName: priceHt
                    beautyName: Prix HT
                    type: money
                unity:
                    dataName: unity
                    beautyName: Unité
                    type: string
                category:
                    dataName: category
                    beautyName: Catégorie
                    type: string
                provider:
                    dataName: provider
                    beautyName: Fournisseur
                    type: string
        provider:
            beautyName: Fournisseurs
            menu: provider
            class: LL\CoreBundle\Entity\Provider
            form: LL\CoreBundle\Form\ProviderType
            views: default
            listProperties:
                name:
                    dataName: name
                    beautyName: Nom
                    type: string
        production:
            beautyName: Fiche de fabrication
            menu: production
            class: LL\CoreBundle\Entity\Production
            form: LL\CoreBundle\Form\ProductionType
            views: production 
            listProperties:
                name:
                    dataName: name
                    beautyName: Nom
                    type: string
                category:
                    dataName: category
                    beautyName: Catégorie
                    type: string
                cookingTime:
                    dataName: cookingTime
                    beautyName: Tps de cuisson
                    type: time
                preparationTime:
                    dataName: preparationTime
                    beautyName: Tps de préparation
                    type: time
#        HostCapacity:
#            menu: hostOptions
#            class: LE\CoreBundle\Entity\HostCapacity
#            form: LE\AdminBundle\Form\HostCapacityType
#            listProperties:
#                labelMax:
#                    dataName: label
#                    beautyName: label
#                    type: string
#                valueMin:
#                    dataName: valueMin
#                    beautyName: valeur min
#                    type: integer
#                valueMax:
#                    dataName: valueMax
#                    beautyName: valeur max
#                    type: integer
#                    
#        Facility:
#            menu: hostOptions
#            class: LE\CoreBundle\Entity\Facility
#            form: LE\AdminBundle\Form\FacilityType
#            listProperties:
#                name:
#                    dataName: name
#                    beautyName: Nom
#                    type: string
#                isFiltered:
#                    dataName: isFiltered
#                    beautyName: Filtre?
#                    type: string
#        Activity:
#            menu: hostOptions
#            class: LE\CoreBundle\Entity\Activity
#            form: LE\AdminBundle\Form\ActivityType
#            listProperties:
#                name:
#                    dataName: name
#                    beautyName: Nom
#                    type: string
#        Divers:
#            menu: hostOptions
#            class: LE\CoreBundle\Entity\Various
#            form: LE\AdminBundle\Form\VariousType
#            listProperties:
#                name:
#                    dataName: name
#                    beautyName: Nom
#                    type: string
#        RestaurationType:
#            menu: hostOptions
#            class: LE\CoreBundle\Entity\RestaurationType
#            form: LE\AdminBundle\Form\RestaurationTypeType
#            listProperties:
#                name:
#                    dataName: name
#                    beautyName: Nom
#                    type: string
#        EventType:
#            menu: hostOptions
#            class: LE\CoreBundle\Entity\EventType
#            form: LE\AdminBundle\Form\EventTypeType
#            listProperties:
#                name:
#                    dataName: name
#                    beautyName: Nom
#                    type: string
#                slug:
#                    dataName: slug
#                    beautyName: Slug
#                    type: string
