<?php

namespace LL\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductQuantityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductQuantityRepository extends EntityRepository
{
}
