<?php

namespace Proxies\__CG__\LL\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \LL\CoreBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'LL\\CoreBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'LL\\CoreBundle\\Entity\\Product' . "\0" . 'name', '' . "\0" . 'LL\\CoreBundle\\Entity\\Product' . "\0" . 'priceHt', '' . "\0" . 'LL\\CoreBundle\\Entity\\Product' . "\0" . 'unity', '' . "\0" . 'LL\\CoreBundle\\Entity\\Product' . "\0" . 'isAllergen', '' . "\0" . 'LL\\CoreBundle\\Entity\\Product' . "\0" . 'productQuantity', '' . "\0" . 'LL\\CoreBundle\\Entity\\Product' . "\0" . 'provider'];
        }

        return ['__isInitialized__', '' . "\0" . 'LL\\CoreBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'LL\\CoreBundle\\Entity\\Product' . "\0" . 'name', '' . "\0" . 'LL\\CoreBundle\\Entity\\Product' . "\0" . 'priceHt', '' . "\0" . 'LL\\CoreBundle\\Entity\\Product' . "\0" . 'unity', '' . "\0" . 'LL\\CoreBundle\\Entity\\Product' . "\0" . 'isAllergen', '' . "\0" . 'LL\\CoreBundle\\Entity\\Product' . "\0" . 'productQuantity', '' . "\0" . 'LL\\CoreBundle\\Entity\\Product' . "\0" . 'provider'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceHt($priceHt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceHt', [$priceHt]);

        return parent::setPriceHt($priceHt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceHt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceHt', []);

        return parent::getPriceHt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnity($unity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnity', [$unity]);

        return parent::setUnity($unity);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnity', []);

        return parent::getUnity();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsAllergen($isAllergen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsAllergen', [$isAllergen]);

        return parent::setIsAllergen($isAllergen);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsAllergen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsAllergen', []);

        return parent::getIsAllergen();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduction(\LL\CoreBundle\Entity\Production $productions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduction', [$productions]);

        return parent::addProduction($productions);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduction(\LL\CoreBundle\Entity\Production $productions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduction', [$productions]);

        return parent::removeProduction($productions);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductions', []);

        return parent::getProductions();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductQuantity(\LL\CoreBundle\Entity\ProductQuantity $productQuantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductQuantity', [$productQuantity]);

        return parent::addProductQuantity($productQuantity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductQuantity(\LL\CoreBundle\Entity\ProductQuantity $productQuantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductQuantity', [$productQuantity]);

        return parent::removeProductQuantity($productQuantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductQuantity', []);

        return parent::getProductQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvider(\LL\CoreBundle\Entity\Provider $provider = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvider', [$provider]);

        return parent::setProvider($provider);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvider()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvider', []);

        return parent::getProvider();
    }

}
