services:
#    ll_core.example:
#        class: LL\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    ll.core.adminMenu:
        class: LL\CoreBundle\Listener\AdminMenu
        arguments: [@security.context,@twig,%ll_core.entities%,%ll_core.menus%]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: showMenu }